# Default configuration for the PPO agent
agent_type: PPO

# Model parameters (shared with A2CModel)
embedding_size: 128

# Optimizer parameters
learning_rate: 3e-4

# PPO specific hyperparameters
discount_factor: 0.99
gae_lambda: 0.95
clip_range: 0.2
entropy_coef: 0.01
value_coef: 0.5
max_grad_norm: 0.5

# Adaptive KL Penalty (Optional)
use_adaptive_kl: false
target_kl: 0.01
initial_kl_coeff: 1.0

