name: reinforce_minigrid
channels:
    - apple
    - conda-forge
dependencies:
    - python>=3.10
    - pip>=19.0
    - tensorflow-deps
    - pip:
        - tensorflow-macos
        - tensorflow-metal
        - minigrid==2.2.1