base_config:
  agent:
    agent_type: A2C
    discount_factor: 0.99
    embedding_size: 128
    learning_rate: 0.001
    entropy_coef: 0.01
    value_coef: 0.5
    gae_lambda: 0.95
    max_grad_norm: 0.5
    lr_schedule_enabled: true
  environment:
    use_image_obs: true
  trainer:
    trainer_type: A2CTrainer
    batch_size: 64
    buffer_capacity: 2048
    max_episodes: 20
    max_steps_per_episode: 200
    update_frequency: 100
    eval_frequency: 100
    num_eval_episodes: 5
    log_frequency: 10
    save_frequency: 500
    save_dir: outputs/models/a2c_search_temp

hyperparameters:
  agent.learning_rate:
    type: float
    low: 1.0e-5
    high: 0.005
    log_scale: true
  agent.entropy_coef:
    type: float
    low: 0.001
    high: 0.05
    log_scale: true
  agent.embedding_size:
    type: int
    low: 64
    high: 256
    step: 64
  agent.value_coef:
    type: float
    low: 0.25
    high: 0.75
  agent.discount_factor:
    type: categorical
    values:
      - 0.95
      - 0.99
      - 0.995
  agent.gae_lambda:
    type: float
    low: 0.9
    high: 0.99
  agent.max_grad_norm:
    type: float
    low: 0.5
    high: 1.0
  agent.lr_schedule_enabled:
    type: bool
  trainer.buffer_capacity:
    type: int
    low: 512
    high: 4096
    step: 512
  trainer.batch_size:
    type: categorical
    values:
      - 32
      - 64
      - 128
