# Default configuration for PPO evaluation on Maze environment
# This file can be passed using --config path/to/eval_config.yaml
# Command-line arguments will override settings in this file.

# --- Core Evaluation Parameters ---
env_id: "Maze-v0"
num_episodes: 10      # Number of episodes to evaluate
render: false         # Render environment during evaluation
seed: 123             # Use a different seed for evaluation than training
load_dir: "checkpoints" # Directory containing saved weights
weights_prefix: "ppo_maze_epoch_50" # Specific weights file prefix (e.g., from last epoch)
max_episode_steps: 200 # Maximum steps per evaluation episode

# --- GIF Saving Parameters ---
save_gif: false       # Whether to save a GIF of the evaluation episodes
gif_path: "evaluation.gif" # Path to save the evaluation GIF

# --- Network Parameters ---
# These MUST match the parameters of the saved/trained model being loaded
conv_filters: 32
conv_kernel_size: 3
dense_units: 128
