agent:
  agent_type: A2C
  embedding_size: 120
  learning_rate: 0.007858792303576312
  entropy_coef: 0.025988745164565022
  value_coef: 0.6794738331252752
  discount_factor: 0.9
environment:
  use_image_obs: true
trainer:
  trainer_type: A2CTrainer
  max_episodes: 20
  max_steps_per_episode: 200
  buffer_capacity: 10
  max_total_steps: 1000
  update_frequency: 25
  eval_frequency: 100
  num_eval_episodes: 3
  batch_size: 32
  log_frequency: 10
  save_frequency: 500
  save_dir: outputs/models/a2c_final
  save_path: outputs/models/a2c_final