agent:
  agent_type: PPO
  embedding_size: 107
  learning_rate: 1.0e-05  # Reduced learning rate
  gae_lambda: 0.9
  clip_range: 0.1  # Reduced clip range for more stability
  entropy_coef: 0.01
  value_coef: 0.5
  max_grad_norm: 0.5
  gamma: 0.99
environment:
  use_image_obs: true
trainer:
  trainer_type: PPOTrainer
  n_steps: 128
  n_epochs: 3  # Fewer epochs per update
  batch_size: 32
  max_total_steps: 1000
  max_steps_per_episode: 200
  eval_frequency: 100
  num_eval_episodes: 3
  log_frequency: 10
  save_frequency: 500
  save_dir: outputs/models/stable_ppo
  save_path: outputs/models/stable_ppo