base_config:
  agent:
    agent_type: A2C
    action_space: 6
    embedding_size: 128
    learning_rate: 0.001
    discount_factor: 0.99
    entropy_coef: 0.01
    value_coef: 0.5
  environment:
    use_image_obs: true
  trainer:
    trainer_type: EpisodeTrainer
    max_episodes: 500
    max_steps_per_episode: 100
    update_frequency: 50
    eval_frequency: 100
    num_eval_episodes: 5
    gamma: 0.99
    log_frequency: 100
    save_frequency: 500
    save_dir: outputs/models
  save_results: true
  results_dir: outputs/results
hyperparameters:
  agent.learning_rate:
    type: float
    low: 0.0001
    high: 0.01
    log_scale: true
  agent.entropy_coef:
    type: float
    low: 0.001
    high: 0.1
    log_scale: true
  agent.discount_factor:
    type: categorical
    values:
    - 0.9
    - 0.95
    - 0.99
  agent.embedding_size:
    type: int
    low: 64
    high: 256
